// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiRN9gdYQxAWFU3zbytwg5TGNXJ8uZtsY',
    appId: '1:233409468768:web:c7f0e3546274cbdfbae605',
    messagingSenderId: '233409468768',
    projectId: 'amazing-coffee-ebdea',
    authDomain: 'amazing-coffee-ebdea.firebaseapp.com',
    storageBucket: 'amazing-coffee-ebdea.firebasestorage.app',
    measurementId: 'G-4QWTT4KPHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOX7TfN1TleJRX4-AAHmxXrU4lYc55mw',
    appId: '1:233409468768:android:83ea3796039f1ba6bae605',
    messagingSenderId: '233409468768',
    projectId: 'amazing-coffee-ebdea',
    storageBucket: 'amazing-coffee-ebdea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTjseNTgCGRBI-nJmNJ-X354Lb-wPDd8Q',
    appId: '1:233409468768:ios:64ccde391f7cfab1bae605',
    messagingSenderId: '233409468768',
    projectId: 'amazing-coffee-ebdea',
    storageBucket: 'amazing-coffee-ebdea.firebasestorage.app',
    androidClientId: '233409468768-khihr68qpogks3fpq1f36ot7p70iu7a9.apps.googleusercontent.com',
    iosClientId: '233409468768-a7blsuke4d464sd0n7a3469hfnkbdba6.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTjseNTgCGRBI-nJmNJ-X354Lb-wPDd8Q',
    appId: '1:233409468768:ios:64ccde391f7cfab1bae605',
    messagingSenderId: '233409468768',
    projectId: 'amazing-coffee-ebdea',
    storageBucket: 'amazing-coffee-ebdea.firebasestorage.app',
    androidClientId: '233409468768-khihr68qpogks3fpq1f36ot7p70iu7a9.apps.googleusercontent.com',
    iosClientId: '233409468768-a7blsuke4d464sd0n7a3469hfnkbdba6.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiRN9gdYQxAWFU3zbytwg5TGNXJ8uZtsY',
    appId: '1:233409468768:web:0cc5c205376e8a7fbae605',
    messagingSenderId: '233409468768',
    projectId: 'amazing-coffee-ebdea',
    authDomain: 'amazing-coffee-ebdea.firebaseapp.com',
    storageBucket: 'amazing-coffee-ebdea.firebasestorage.app',
    measurementId: 'G-8TX4PCGNZ9',
  );
}
